import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import NormalLayout from "@/components/layouts/NormalLayout";
import HomeComponent from "@/components/home/Home";
import Header from "@/components/common/header/Header";
import Footer from "@/components/common/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NormalLayout>
          {/* <Header /> */}
          <HomeComponent />
          {/* <Footer /> */}
        </NormalLayout>
      </main>
    </>
  );
}
