import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import NormalLayout from "@/components/layouts/NormalLayout";
import BlogDetailComponent from "@/components/page/Blogs/BlogDetail";
import BreadCrumbContainer from "@/components/utils/BreadCrumbContainer";
import { useRouter } from "next/router";
import { blogs } from "@/data/Data";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import {
  getBlogDetail,
  getFetchedBlogDetail,
} from "@/store/features/blogSlice";

const inter = Inter({ subsets: ["latin"] });

export default function BlogDetail() {
  const router = useRouter();
  const { _id } = router.query;
  const dispatch = useDispatch();
  const blogs = useSelector((state) => state.blog.blogs);

  useEffect(() => {
    if (_id) {
      const index = blogs?.findIndex((item) => item?._id === _id);
      if (index === -1) {
        dispatch(getBlogDetail(_id));
      } else {
        dispatch(getFetchedBlogDetail(_id));
      }
    }
  }, [_id, blogs, dispatch]);

  const blogDetail = useSelector((state) => state.blog.detail);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NormalLayout>
          <BreadCrumbContainer />
          {/* <Header /> */}
          <BlogDetailComponent blog={blogDetail} />
          {/* <Footer /> */}
        </NormalLayout>
      </main>
    </>
  );
}
